# Generated by Django 2.0.5 on 2019-01-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_capacity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MotorInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_mobile_number', models.IntegerField()),
                ('vehicle_model', models.CharField(max_length=50)),
                ('cc_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_insurance_app.Capacity')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_insurance_app.Coverage')),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_insurance_app.DeliveryType')),
            ],
        ),
        migrations.CreateModel(
            name='PassangerSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passanger_seat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TonCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ton_capacity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegistrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='motorinsurance',
            name='passanger_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_insurance_app.PassangerSeat'),
        ),
        migrations.AddField(
            model_name='motorinsurance',
            name='registration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_insurance_app.VehicleRegistrationType'),
        ),
        migrations.AddField(
            model_name='motorinsurance',
            name='ton_capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_insurance_app.TonCapacity'),
        ),
        migrations.AddField(
            model_name='motorinsurance',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_insurance_app.Vehicle'),
        ),
    ]
