# Generated by Django 2.1.5 on 2019-01-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle',
            new_name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='motorinsurance',
            name='cc_capacity',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='motorinsurance',
            name='coverage',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='motorinsurance',
            name='delivery_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='motorinsurance',
            name='passanger_seat',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='motorinsurance',
            name='registration_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='motorinsurance',
            name='ton_capacity',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='motorinsurance',
            name='vehicle_type',
            field=models.CharField(max_length=30),
        ),
    ]
